[package]
name = "cms"
version = "0.1.0"
edition = "2021"
description = "sreaming heavy hitters"
authors = ["Darian Harrison <darianharrison89@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fasthash = "0.4"
